Cg/http client logger test
resurfaceio/logger-go pull request #29
Opened 2021-03-03 00:28 UTC by ChandlerGarthwaite

This is a copy from the previous PR. Changed File name and corrected merge into test not master

2021-03-03 02:27 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	assert.Equal(t, helper.mockAgent, httpLogger.Agent())
you shouldn't need the test helper here you can just use `httpLogger.agent`, you are essentially testing the getter here.

2021-03-03 02:29 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	logger1 := NewHttpLogger(url1)
Go doesn't allow overloading to these constructors will have to have the names of the parameters in their name, specifically here the names will be `NewHttpLoggerUrl`

2021-03-03 02:30 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	assert.Equal(t, helper.mockAgent, logger1.AGENT())
again just use `logger1.agent`

2021-03-03 02:31 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	assert.Equal(t, helper.mockAgent, logger1.AGENT())
if you disagree just let me know

2021-03-03 02:40 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	assert.Nil(t, logger3.Url())
this shouldn't be here?

2021-03-03 02:46 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +
you should still have the test using `UsageLoggers.disable/enable`

2021-03-03 02:48 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	logger1 := NewHttpLogger()
`httpLogger = NewHttpLoggger()`

2021-03-03 02:48 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	agent := helper.mockAgent
`agent := httpLogger.agent`

2021-03-08 14:51 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	agent := httpLogger.mockAgent
should be `agent := httpLogger.agent`

2021-03-10 04:53 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	UsageLoggers.disable()
`UsageLoggers`'s enabled and disabled should be public so 
`UsageLoggers.Disable()`
and `UsageLoggers.Enable()`

2021-03-10 04:59 UTC, tblenahan commented on src/logger/HttpLogger_test.go
> +	httpLogger := NewHttpLogger()
`httpLogger := NewHttpLogger(Options{})`

2021-03-10 05:02 UTC, tblenahan requested changes
A little more context for this PR would be nice in the actual PR description.

See my comments for the last few changes.

2021-03-11 16:50 UTC, KyleNeubarth approved these changes

2021-03-12 05:10 UTC, tblenahan approved these changes
Looks good! Thank you @ChandlerGarthwaite

2021-03-12 05:10 UTC, merged